-- 코드를 입력하세요
SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
FROM ANIMAL_OUTS a
RIGHT JOIN ANIMAL_INS b ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE b.SEX_UPON_INTAKE LIKE 'Intact%'
AND a.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY a.ANIMAL_ID;