-- 코드를 입력하세요
SELECT DISTINCT a.CAR_ID, a.CAR_TYPE,
FLOOR((a.DAILY_FEE * 30) * (1 - c.DISCOUNT_RATE * 0.01)) AS 'FEE'
FROM CAR_RENTAL_COMPANY_CAR a
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c ON a.CAR_TYPE = c.CAR_TYPE
WHERE
a.CAR_ID NOT IN (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-11-30' 
    AND END_DATE >= '2022-11-01'
)
AND c.DURATION_TYPE LIKE '30일%'
AND a.CAR_TYPE IN ('세단', 'SUV')
AND 
    (a.DAILY_FEE * 30) * (1 - c.DISCOUNT_RATE * 0.01) >= 500000
AND 
    (a.DAILY_FEE * 30) * (1 - c.DISCOUNT_RATE * 0.01) < 2000000
ORDER BY FEE DESC, a.CAR_TYPE ASC, a.CAR_ID DESC
;