-- 코드를 작성해주세요
SELECT a.ID AS ID, b.FISH_NAME, a.LENGTH AS LENGTH
FROM FISH_INFO a
JOIN FISH_NAME_INFO b ON a.FISH_TYPE = b.FISH_TYPE
WHERE a.LENGTH > 1
AND a.LENGTH = (
    SELECT MAX(a2.LENGTH)
    FROM FISH_INFO a2
    WHERE a.FISH_TYPE = a2.FISH_TYPE
    GROUP BY a2.FISH_TYPE
)
ORDER BY a.ID